services:
  custom-llm-api:
    container_name: custom-llm-api
    image: evdev3/custom-llm-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
    env_file:
      - .env